name: Publish 

on:
  workflow_dispatch:
  push:
    branches:
    - master

env:
  AZURE_WEBAPP_NAME: bawl
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  publish:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
       
      - name: Setup .NET
        uses: actions/setup-dotnet@master
        with: 
          dotnet-version: '6.0.x'
          
      - name: Restore
        run: dotnet restore BawlAPI
        
      - name: Build
        run: dotnet build BawlAPI --configuration Release --no-restore
       
      - name: Publish
        run: dotnet publish BawlAPI -c Release -o '${{env.DOTNET_ROOT}}/BawlAPI'
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: '${{env.DOTNET_ROOT}}/BawlAPI'
     
     
        
      
        
      
          
 
     
     
